### PR TITLE
Repo logic overhaul

### PR DESCRIPTION
**Pull request by Ryther**
1. Separated the app logic from the docker container creation;
   - Modified the Dockerfile to use git clone instead of using the content of this repo;
   - The separation of the app repo from the container creation repo is advised.
2. Reduced image size (from ~400mb to ~60mb);
3. Improved the time to compile a new docker image (after the first build);
4. Addedd s6 layer to the docker image;
5. Used s6 layer to manage docker secrets;
6. Added some info to the README and the example docker-compose.yaml

Big thanks to [LinuxServer.io](https://linuxserver.io) which I used as base to add the use of docker secrets and s6 layer.

### CODE REVIEW

**Comment by wiseindy** [comment]
Thanks for your help! This looks promising, however, I'm having issues building this on my machine. Hoping you can point me in the right direction.

The container continuously restarts. Here are the relevant output after I run `docker-compose up`:

```
Attaching to timer
timer    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
timer    | [s6-init] ensuring user provided files have correct perms...exited 0.
timer    | [fix-attrs.d] applying ownership & permissions fixes...
timer    | [fix-attrs.d] done.
timer    | [cont-init.d] executing container initialization scripts...
timer    | [cont-init.d] 01-envfile: executing...
timer    | foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/01-envfile: No such file or directory
timer    | [cont-init.d] 01-envfile: exited 127.
timer    | [cont-finish.d] executing container finish scripts...
timer    | [cont-finish.d] done.
timer    | [s6-finish] waiting for services.
timer    | [s6-finish] sending all processes the TERM signal.
timer    | [s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by Ryther** [comment]
Which command did you use to build the image? Looks like it didn't copy the `root` folder in the image.
cd into the root directory of the project and use:
```bash
sudo docker build --no-cache -t wiseindy/timer-for-google-assistant:dev .
```

**Comment by Ryther** [comment]
You can also use compose to make it automated:
```yaml
---
version: "3.8"
services:
  timer:
    image: wiseindy/timer-for-google-assistant
    build: https://github.com/wiseindy/timer-for-google-assistant.git#dev
    container_name: timer
    secrets:
      - timer_security_key
      - timer_ifttt_event_key
    environment:
      PORT: 3333
      FILE__SECURITY_KEY: /run/secrets/timer_security_key
      FILE__IFTTT_EVENT_KEY: /run/secrets/timer_ifttt_event_key
      IFTTT_EVENT_OFF_SUFFIX: _off
      IFTTT_EVENT_ON_SUFFIX: _on
    ports:
      - 3020:3333
    restart: unless-stopped

secrets:
  timer_security_key:
    file: ./security_key.secret
  timer_ifttt_event_key:
    file: ./ifttt_event_key.secret
  ...
```
the compose file will build the image based on the dev branch (you need to delete all the images with the name of `wiseindy/timer-for-google-assistant`)

**Comment by wiseindy** [comment]
Yeah it does seem to be an issue with s6 and I'm still investigating it. I didn't get much time over the weekend. Will look into this now and hope to have it resolved soon.

Btw, are you running Docker on Linux or Windows?

**Comment by Ryther** [comment]
> 
> 
> Yeah it does seem to be an issue with s6 and I'm still investigating it. I didn't get much time over the weekend. Will look into this now and hope to have it resolved soon.
> 
> Btw, are you running Docker on Linux or Windows?

I'm running both, Docker on Linux with an Ubuntu server 20.04 and Docker for Windows (CMD and WSL2); ~I've built the image with both systems without problem~. If I try to build it from the repository using , I get this error:
> Recreating timer ... done
> Attaching to timer
> timer    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> timer    | [s6-init] ensuring user provided files have correct perms...exited 0.
> timer    | [fix-attrs.d] applying ownership & permissions fixes...
> timer    | [fix-attrs.d] done.
> timer    | [cont-init.d] executing container initialization scripts...
> timer    | [cont-init.d] 01-envfile: executing...
> timer    | [env-init] IFTTT_EVENT_KEY set from FILE__IFTTT_EVENT_KEY
> timer    | [env-init] SECURITY_KEY set from FILE__SECURITY_KEY
> timer    | [cont-init.d] 01-envfile: exited 0.
> timer    | [cont-init.d] 10-adduser: executing...
> timer    | foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/10-adduser: Permission denied
> timer    | [cont-init.d] 10-adduser: exited 127.
> timer    | [cont-finish.d] executing container finish scripts...
> timer    | [cont-finish.d] done.
> timer    | [s6-finish] waiting for services.
> timer    | [s6-finish] sending all processes the TERM signal.
> timer    | [s6-finish] sending all processes the KILL signal and exiting.

Otherwise, if I try to build it from local, everything run smoothly.

```bash
sudo docker build --no-cache -t wiseindy/timer-for-google-assistant https://github.com/wiseindy/timer-for-google-assistant.git#dev
```

This one does not work, showing the problem above.


```bash
sudo docker build --no-cache -t wiseindy/timer-for-google-assistant .
```

This one works ok

**Comment by wiseindy** [comment]
> If I try to build it from the repository, I get this error:
...
timer | foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/10-adduser: Permission denied
...

Yep. I get the same "Permission denied" error when building from the repo. We have a similar setup. I'm also running Docker for Windows on WSL2 and Docker for Linux on an Ubuntu 18.04 server.

Regarding my original issue, I just wanted to rule out any potential platform/architecture issues, but since we have a similar setup, that doesn't seem to be the problem.

I'll try to get this sorted out. Thanks again for your help!

**Comment by Ryther** [comment]
You're welcome! I think it's a bug in the docker's build command. I've already reported a bug to docker for the build with repo so I think it's something on their end

**Comment by wiseindy** [comment]
I've found the problem. Turns out the files under `root/` were having their line endings and permissions altered which was causing this build issue. I've modified the `Dockerfile` and added steps to `cloner` to convert line endings to `LF` and update permissions for all files under `root/`. It seems to work great now.

**Pull request merged**
