### PR TITLE
Set gitattributes

### PR DESCRIPTION
**Pull request by Ryther**
I've tried to set gitattributes to resolve the problem with the line ending.
For the permission, the s6 layer should already set owner and permissions on start.

Give it a try, I've added the `git checkout dev` part in the Dockerfile to test it.

### CODE REVIEW

**Comment by wiseindy** [comment]
Works great! I've done a few changes, fixed the permissions issue and merged the PR.

**Comment by Ryther** [comment]
That's great! As I wrote before, maybe it's better to separate the app repo from the docker image repo. Other than that looks promising... the only bad thing is that IFTTT is going pro and locked to only 3 tasks. I wioll not pay for a service I've already paid for when I bought things like my google home devices etc.
Do you think it is possible to create an integration for home assistant?

**Comment by wiseindy** [comment]
Yeah definitely. I'll work on moving the docker stuff to another repo. Didn't get much time to work on this recently.

And, yeah shame about IFTTT. I had to delete all of my IFTTT tasks. 3 is too less and I need to definitely think of an alternative. I've been considering Home assistant too. I already use it in my home and love it. I'll start working on a home assistant integration soon.

**Comment by Ryther** [comment]
That's good. I'm using home assistant a lot and integrating this will be really good, since home assistant is missing something like this. Sadly I cannot help with the integration, only worked with HA as an user.

**Pull request merged**
